### ISSUE TITLE
FacebookApi is not loaded

### ISSUE THREAD

**Issue by vivekgandhi** [TomGrill/gdx-facebook-app#1]
Hi,

In android, i get FacebookApi not loaded. It works fine in IOS. What would be the problem?

**Comment by TomGrill** [comment]
Hi not enough information to help. Can you copy logcat output or a stacktrace?

**Comment by vivekgandhi** [comment]
Hi,

This is what I get in Logcat.

06-19 05:08:21.931: D/libGDX Facebook(693): Error creating FacebookAPI for Android (are the libGDX Facebook **.jar files installed?). 
06-19 05:08:21.931: W/System.err(693): com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in constructor for class: de.tomgrill.gdxfacebook.android.AndroidFacebookAPI
06-19 05:08:21.932: W/System.err(693):  at com.badlogic.gdx.utils.reflect.Constructor.newInstance(Constructor.java:62)
06-19 05:08:21.932: W/System.err(693):  at de.tomgrill.gdxfacebook.core.FacebookSystem.tryLoadAndroidFacebookAPI(FacebookSystem.java:172)
06-19 05:08:21.932: W/System.err(693):  at de.tomgrill.gdxfacebook.core.FacebookSystem.<init>(FacebookSystem.java:45)
06-19 05:08:21.932: W/System.err(693):  at de.tomgrill.gdxfacebook.app.GdxFacebookSampleApp.create(GdxFacebookSampleApp.java:70)
06-19 05:08:21.932: W/System.err(693):  at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:241)
06-19 05:08:21.932: W/System.err(693):  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1511)
06-19 05:08:21.932: W/System.err(693):  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
06-19 05:08:21.932: W/System.err(693): Caused by: java.lang.reflect.InvocationTargetException
06-19 05:08:21.933: W/System.err(693):  at java.lang.reflect.Constructor.newInstance(Native Method)
06-19 05:08:21.933: W/System.err(693):  at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
06-19 05:08:21.933: W/System.err(693):  at com.badlogic.gdx.utils.reflect.Constructor.newInstance(Constructor.java:53)
06-19 05:08:21.933: W/System.err(693):  ... 6 more
06-19 05:08:21.933: W/System.err(693): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookSdk;
06-19 05:08:21.933: W/System.err(693):  at de.tomgrill.gdxfacebook.android.AndroidFacebookAPI.<init>(AndroidFacebookAPI.java:48)
06-19 05:08:21.933: W/System.err(693):  ... 9 more
06-19 05:08:21.933: W/System.err(693): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookSdk" on path: DexPathList[[zip file "/data/app/com.elifantasy.mathcar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.elifantasy.mathcar-1/lib/arm, /vendor/lib, /system/lib]]
06-19 05:08:21.934: W/System.err(693):  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-19 05:08:21.934: W/System.err(693):  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-19 05:08:21.934: W/System.err(693):  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-19 05:08:21.934: W/System.err(693):  ... 10 more
06-19 05:08:21.934: W/System.err(693):  Suppressed: java.lang.ClassNotFoundException: com.facebook.FacebookSdk
06-19 05:08:21.941: W/System.err(693):      at java.lang.Class.classForName(Native Method)
06-19 05:08:21.941: W/System.err(693):      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-19 05:08:21.941: W/System.err(693):      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-19 05:08:21.941: W/System.err(693):      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-19 05:08:21.941: W/System.err(693):      ... 11 more

**Comment by TomGrill** [comment]
Do you run the gdx-facebook-app example of this repository or do you implement the gdx-facebook extension to your own project?

This line makes me think: /data/app/com.elifantasy.mathcar-1/base.apk

Are we on the same page?

Can you post the android part of the build.gradle?

**Comment by vivekgandhi** [comment]
Its the same sample app. Since it didnt work, i tried renaming the package to match my appid.

**Comment by TomGrill** [comment]
Ok for some reason the FacebookSDK is not loaded. Which should be accomplished with this line:

`compile ("com.facebook.android:facebook-android-sdk:4.1.0")`

Is proguard enabled?

**Comment by vivekgandhi** [comment]
Progaurd is not enabled. By default the sample app will have this compile line right?

**Comment by TomGrill** [comment]
yes

**Comment by TomGrill** [comment]
Could you solve the problem?

**Comment by TomGrill** [comment]
I close this issue. If it still exists with 0.3.0 please reopen a new issue.
