### ISSUE TITLE
gdx-facebook not installed error

### ISSUE THREAD

**Issue by WaZz86** [TomGrill/gdx-facebook-app#2]
Hello, 
I have done all the necessary things to set up the facebook sample app but i am running into this error when i run the app and i get these messages in logcat:

Error installing gdx-facebook for Android

Did you add compile >> "de.tomgrill.gdxfacebook:gdx-facebook-android:0.3.0-SNAPSHOT" << to your gradle dependencies?

READ REQUEST: Error login: gdx-facebook not installed

I haven't changed anything from the sample app, is there something i might be missing here?

**Comment by TomGrill** [comment]
Hi this error is known to me. Did not solve it so far. Since everthing works for me its not easy to look for the reason. Do you use mac?

**Comment by WaZz86** [comment]
Hi,
No i am using a PC with windows 7 64 bit and my IDE: is Eclipse

**Comment by TomGrill** [comment]
I looked into it and found the reason: 

facebook-android-sdk comes as .aar file and Eclipse is not capable to handle these kind of files. So you have to use command line to start the app or the required facebook sdk will not be available in your apk. 

Linux/Max:
`./gradlew android:installDebug android:run`

Windows:
`gradlew android:installDebug android:run`

I will update the readme accordingly.

I hope this helps

**Comment by itsabhiaryan** [comment]
Working fine if I am using `./gradlew android:installDebug android:run` on my Mac system.

What about release ?? I am getting above error on release apk. How I build apk/bundle that contains `.aar` file.

gdx-facebook : **1.4.1** and **1.5.0** (I tried both version)
IDE : **AS 3.5**

@TomGrill Can you guide me what should I do now.
